server:
  port: 8887
  servlet:
    context-path: /personalStudy
spring:
  application:
    name: personalStudy
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10000